service: pull-farsetlabs-events
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "FarsetlabsEventsBucket"
            - "/*"
functions:
  produce:
    handler: handler.produce
    events:
      - schedule: rate(1 hour)
    environment:
      TZ: Europe/Belfast
resources:
  Resources:
    FarsetlabsEventsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: farsetlabs-events-bucket
