service: pull-meetupcom-events
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "MeetupcomEventsBucket"
            - "/*"
functions:
  produce:
    handler: handler.produce
    events:
      - schedule: rate(1 hour)
    environment:
      TZ: Europe/Belfast
      MEETUPCOM_API_TOKEN: ${ssm:meetupcomApiToken~true}
resources:
  Resources:
    MeetupcomEventsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: meetupcom-events-bucket
